# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named themes
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

discovery:
history:
logbook:
map:
sun:
system_health:
person:
ios:
cloud:
stream:
sensor: !include_dir_merge_list sensors/

# Text to speech
tts: !include_dir_merge_list tts/
switch: !include_dir_merge_list switches/
twilio: !include_dir_merge_named twilio/
device_tracker: !include_dir_merge_list device_trackers/
light: !include_dir_merge_list lights/
ifttt: !include_dir_merge_named ifttt/
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include_dir_merge_named input_number/
notify: !include_dir_merge_list notify/
recorder: !include_dir_merge_named recorder/
group: !include_dir_merge_named groups/
zone: !include_dir_merge_list zones/
climate: !include_dir_merge_list climate/
weather: !include_dir_merge_list weather/
automation: !include_dir_merge_list automations/
life360: !include_dir_merge_list life360/
google: !include_dir_merge_named google/
hacs: !include_dir_merge_named hacs/
script: !include_dir_merge_named scripts/
alarm_control_panel: !include_dir_merge_list alarm_control_panels/
media_player: !include_dir_merge_list media_players
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: https://hassio.newvalleyresources.com:9541
#logger: