- platform: history_stats
  name: jon_hours_this_week
  entity_id: device_tracker.life360_jon
  state: 'New Valley Chandler'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'

- platform: history_stats
  name: jon_hours_this_month
  entity_id: device_tracker.life360_jon
  state: 'New Valley Chandler'
  type: time
  start: '{{ as_timestamp( now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'

- platform: history_stats
  name: jon_hours_this_year
  entity_id: device_tracker.life360_jon
  state: 'New Valley Chandler'
  type: time
  start: '{{ as_timestamp( now().replace(month=1).replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'

- platform: history_stats
  name: jon_hours_all_time
  entity_id: device_tracker.life360_jon
  state: 'New Valley Chandler'
  type: time
  start: '{{ 0 }}'
  end: '{{ now() }}'