- platform: mqtt
  state_topic: "newvalley/sensornode1"
  name: "SN1 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "newvalley/sensornode1"
  name: "SN1 LDR"
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "newvalley/sensornode1"
  name: "SN1 PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "newvalley/sensornode1"
  name: "SN1 Temperature"
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "newvalley/sensornode1"
  name: "SN1 Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'